### ISSUE TITLE
Question about License

### ISSUE THREAD

**Issue by beginner-jp986** [ErencanPelin/Full-Inventory-System-for-Unity#1]
Hello,

I am developing a game with Unity in Japan. I would like to use the code available on your GitHub for creating an inventory system. Due to concerns regarding licensing, I am sending this message to seek your permission. If I may use the code, could you please let me know any conditions or requirements that need to be fulfilled?

**Comment by ErencanPelin** [comment]
Hi there! Thanks for reaching out! The project sticks to the BSD 3 clause license. I've just added the license file as well. You can check out the full details here: [License](https://github.com/ErencanPelin/Inventory-System-for-Unity-wScriptableObjects/blob/main/LICENSE)

**Comment by beginner-jp986** [comment]
Thank you for your reply. I appreciate it very much. I respect your
programming skills!

2024年12月29日(日) 6:05 Erencan Pelin ***@***.***>:
